version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      updates:
        applies-to: version-updates
        patterns:
          - "*"
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    groups:
      npm:
        applies-to: version-updates
        patterns:
          - "*"
  - package-ecosystem: nix
    directory: /
    schedule:
      interval: monthly
    groups:
      nix:
        applies-to: version-updates
        patterns:
          - "*"
