name: Publish Release

on:
  push:
    branches:
      - main
      - "main-*"

permissions: {}

jobs:
  publish:
    permissions:
      contents: write
      id-token: write
    uses: holochain/actions/.github/workflows/nodejs-publish-release.yml@e3e5f19ffbf400997ff7a58bdcd489d1ab953eee # v1.17.0
    with:
      build_script: build
