name: Publish Release

on:
  push:
    branches:
      - main
      - "main-*"

permissions: {}

jobs:
  publish:
    permissions:
      contents: write
      id-token: write
    uses: holochain/actions/.github/workflows/nodejs-publish-release.yml@832c0c654691d0ee736a12dab74832a48318fd30 # v1.18.0
    with:
      build_script: build
